# Generated by Django 4.2.11 on 2024-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('specialisation', models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Allergist', 'Allergist'), ('Gastroenterologist', 'Gastroenterologist'), ('Hepatologist', 'Hepatologist'), ('Osteopathic', 'Osteopathic'), ('Endocrinologist', 'Endocrinologist'), ('Pulmonologist', 'Pulmonologist'), ('Cardiologist ', 'Cardiologist '), ('Neurologist', 'Neurologist'), ('Internal Medcine', 'Internal Medcine'), ('Pediatrician', 'Pediatrician'), ('Common Cold', 'Common Cold'), ('Cardiologist', 'Cardiologist'), ('Phlebologist', 'Phlebologist'), ('Osteoarthristis', 'Osteoarthristis'), ('Rheumatologists', 'Rheumatologists'), ('Otolaryngologist', 'Otolaryngologist'), ('Dermatologists', 'Dermatologists'), ('Gynecologist', 'Gynecologist')], max_length=500)),
            ],
        ),
    ]
